[package]
name = "kmux-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kmux-server"
path = "src/main.rs"

[features]
default = ["backend-alacritty"]
backend-alacritty = ["dep:alacritty_terminal"]
backend-termwiz = ["dep:termwiz"]

[dependencies]
kmux-pty.workspace = true
kmux-protocol = { workspace = true, features = ["framing"] }
daemonize.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
alacritty_terminal = { workspace = true, optional = true }
termwiz = { workspace = true, optional = true }
tokio.workspace = true
quinn.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
rcgen.workspace = true
rand.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile.workspace = true
