[package]
name = "kmux-pty"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "PTY management for kmux."

[features]
serde = ["dep:serde"]

[dependencies]
tokio.workspace = true
nix.workspace = true
thiserror.workspace = true
serde = { workspace = true, optional = true }
