name      = "catppuccin-frappe"
bg        = "#303446"
fg        = "#c6d0f5"
fg_dim    = "#737994"
accent    = "#8caaee"
green     = "#a6d189"
red       = "#e78284"
yellow    = "#e5c890"
purple    = "#ca9ee6"
orange    = "#ef9f76"
status_bg = "#292c3c"
