name      = "catppuccin-latte"
bg        = "#eff1f5"
fg        = "#4c4f69"
fg_dim    = "#9ca0b0"
accent    = "#1e66f5"
green     = "#40a02b"
red       = "#d20f39"
yellow    = "#df8e1d"
purple    = "#8839ef"
orange    = "#fe640b"
status_bg = "#e6e9ef"
