name      = "catppuccin-macchiato"
bg        = "#24273a"
fg        = "#cad3f5"
fg_dim    = "#6e738d"
accent    = "#8aadf4"
green     = "#a6da95"
red       = "#ed8796"
yellow    = "#eed49f"
purple    = "#c6a0f6"
orange    = "#f5a97f"
status_bg = "#1e2030"
