#!/bin/sh
# Render the Homebrew formula + cask for getkono/homebrew-tap from a release's
# checksums. The single source of truth for both files: the release workflow's
# update-tap job runs this against the published .sha256 sidecars and commits the
# output into the tap. Run it by hand to seed the tap for the first time.
#
#   packaging/homebrew/render.sh <out-dir>
#
# Environment:
#   VERSION                          release version, e.g. 0.2.0 (required)
#   SHA_TAR_ARM_MAC / SHA_TAR_X86_MAC   sha256 of the macOS CLI tarballs (formula)
#   SHA_TAR_ARM_LIN / SHA_TAR_X86_LIN   sha256 of the Linux CLI tarballs (formula)
#   SHA_DMG_ARM / SHA_DMG_X86           sha256 of the signed macOS .dmg (cask)
#
# The cask is only rendered when the dmg checksums are present (i.e. once a
# signed/notarized release exists); the formula is always rendered.
set -eu

out=${1:?usage: render.sh <out-dir>}
: "${VERSION:?VERSION is required}"
rel="https://github.com/getkono/kmux/releases/download"

mkdir -p "$out/Formula" "$out/Casks"

cat > "$out/Formula/kmux.rb" <<EOF
# Generated by packaging/homebrew/render.sh — do not edit by hand.
# CLI + daemon (headless) for macOS and Linuxbrew. The desktop GUI is the cask on
# macOS, and native distro packages / flatpak on Linux.
class Kmux < Formula
  desc "Terminal multiplexer and remote desktop (CLI + daemon)"
  homepage "https://github.com/getkono/kmux"
  version "${VERSION}"
  license "AGPL-3.0-only OR LicenseRef-Commercial"

  on_macos do
    on_arm do
      url "${rel}/v#{version}/kmux-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_TAR_ARM_MAC:-MISSING}"
    end
    on_intel do
      url "${rel}/v#{version}/kmux-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_TAR_X86_MAC:-MISSING}"
    end
  end

  on_linux do
    on_arm do
      url "${rel}/v#{version}/kmux-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_TAR_ARM_LIN:-MISSING}"
    end
    on_intel do
      url "${rel}/v#{version}/kmux-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_TAR_X86_LIN:-MISSING}"
    end
  end

  conflicts_with cask: "kmux", because: "both install a kmux binary"

  def install
    # Keep the relocatable tarball layout intact in libexec so kmuxd finds its
    # sibling libkmux_ghostty (rpath \$ORIGIN/@loader_path) and kmux-vt-worker;
    # expose only the CLI + daemon on PATH. The GTK GUI (Linux) stays unlinked.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"kmux"
    bin.install_symlink libexec/"kmuxd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kmux --version")
  end
end
EOF
echo "==> wrote $out/Formula/kmux.rb"

if [ -n "${SHA_DMG_ARM:-}" ] && [ -n "${SHA_DMG_X86:-}" ]; then
    cat > "$out/Casks/kmux.rb" <<EOF
# Generated by packaging/homebrew/render.sh — do not edit by hand.
# The signed/notarized macOS desktop app. Includes the daemon + CLI; the binary
# stanza puts \`kmux\` on PATH from inside the bundle.
cask "kmux" do
  arch arm: "aarch64", intel: "x86_64"

  version "${VERSION}"
  on_arm do
    sha256 "${SHA_DMG_ARM}"
  end
  on_intel do
    sha256 "${SHA_DMG_X86}"
  end

  url "${rel}/v#{version}/kmux-#{version}-#{arch}-apple-darwin.dmg"
  name "kmux"
  desc "Terminal multiplexer and remote desktop with a native GUI"
  homepage "https://github.com/getkono/kmux"

  depends_on macos: ">= :sonoma"

  app "kmux.app"
  binary "#{appdir}/kmux.app/Contents/MacOS/kmux"

  zap trash: [
    "~/.config/kmux",
    "~/Library/Application Support/dev.getkono.kmux",
    "~/Library/Caches/dev.getkono.kmux",
  ]
end
EOF
    echo "==> wrote $out/Casks/kmux.rb"
else
    echo "==> skipped Casks/kmux.rb (no dmg checksums — needs a signed release)" >&2
fi
