[package]
name = "kmux-client"
version = "0.1.0"
edition = "2024"

[dependencies]
kmux-protocol = { workspace = true, features = ["framing"] }
tokio.workspace = true
quinn.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
tracing.workspace = true
bitflags.workspace = true
